In [4]:
import pandas as pd

In [6]:
data = pd.read_csv("datos_2023-07-10_a_2026-02-04.csv")
data

,Unnamed: 0.1,Unnamed: 0,date,title,ma,axp,cof
0,0,0,2026-02-04,Behavioral Biometrics Market to Reach US$ 18.3...,positive,NaN,NaN
1,1,1,2026-02-03,Here's Why Mastercard Stock Is Still a Buy Des...,positive,negative,negative
2,2,2,2026-02-02,Why a 2.1% Portfolio Shift Targets a New ETF W...,positive,NaN,NaN
3,3,3,2026-02-01,Affiance Financial Bets $43 Million on Chuck A...,positive,NaN,NaN
4,4,4,2026-02-01,This Low-Cost Dividend ETF Can Be a Surprising...,positive,NaN,NaN
...,...,...,...,...,...,...,...
945,945,945,2023-07-13,1 Spectacular Warren Buffett Dividend Stock Th...,NaN,NaN,NaN
946,946,946,2023-07-11,MasterCard (MA) Outpaces Stock Market Gains: W...,NaN,NaN,NaN
947,947,947,2023-07-11,Mastercard (MA) & JazzCash to Speed Up Digitiz...,NaN,NaN,NaN
948,948,948,2023-07-11,This 6.2% AI Dividend Pays Us Every Month,NaN,NaN,NaN
949,949,949,2023-07-10,Mastercard (MA) and DET Launch Unique Digital ...,NaN,NaN,NaN

In [4]:
rango_fechas = pd.date_range(start="2023-07-10",end="2026-02-04", freq="D")

In [5]:
rango_fechas

DatetimeIndex(['2023-07-10', '2023-07-11', '2023-07-12', '2023-07-13',
               '2023-07-14', '2023-07-15', '2023-07-16', '2023-07-17',
               '2023-07-18', '2023-07-19',
               ...
               '2026-01-26', '2026-01-27', '2026-01-28', '2026-01-29',
               '2026-01-30', '2026-01-31', '2026-02-01', '2026-02-02',
               '2026-02-03', '2026-02-04'],
              dtype='datetime64[ns]', length=941, freq='D')

In [30]:
fechas_faltantes = [date for date in rango_fechas if str(date)[:10] not in [date_normal[:10] for date_normal in data.date]]

fechas_faltantes

In [33]:
rango_fechas[:2]

DatetimeIndex(['2023-07-10', '2023-07-11'], dtype='datetime64[ns]', freq='D')

In [32]:
len(fechas_faltantes)

467

In [35]:
def convertir_fechas(fechas):
    return [str(fecha)[:10] for fecha in fechas]

In [36]:
prueba = convertir_fechas(fechas_faltantes)

In [37]:
prueba

['2023-07-12',
 '2023-07-29',
 '2023-07-30',
 '2023-08-01',
 '2023-08-06',
 '2023-08-13',
 '2023-08-20',
 '2023-08-24',
 '2023-08-26',
 '2023-08-29',
 '2023-08-30',
 '2023-09-05',
 '2023-09-06',
 '2023-09-08',
 '2023-09-11',
 '2023-09-17',
 '2023-09-24',
 '2023-10-07',
 '2023-10-08',
 '2023-10-10',
 '2023-10-11',
 '2023-10-21',
 '2023-11-02',
 '2023-11-06',
 '2023-11-19',
 '2023-11-20',
 '2023-11-25',
 '2023-11-26',
 '2023-12-03',
 '2023-12-08',
 '2023-12-23',
 '2023-12-24',
 '2023-12-26',
 '2023-12-30',
 '2024-01-04',
 '2024-01-06',
 '2024-01-07',
 '2024-01-21',
 '2024-02-08',
 '2024-02-09',
 '2024-02-10',
 '2024-02-12',
 '2024-02-14',
 '2024-02-25',
 '2024-03-08',
 '2024-03-09',
 '2024-03-10',
 '2024-03-17',
 '2024-03-22',
 '2024-03-23',
 '2024-03-24',
 '2024-04-08',
 '2024-04-13',
 '2024-04-14',
 '2024-04-20',
 '2024-04-21',
 '2024-04-23',
 '2024-05-05',
 '2024-05-11',
 '2024-05-14',
 '2024-05-18',
 '2024-05-19',
 '2024-05-25',
 '2024-05-26',
 '2024-06-01',
 '2024-06-08',
 '2024-06-09',
 '2024-06-11',
 '2024-06-13',
 '2024-06-15',
 '2024-06-16',
 '2024-06-17',
 '2024-06-21',
 '2024-06-23',
 '2024-06-30',
 '2024-07-02',
 '2024-07-06',
 '2024-07-07',
 '2024-07-11',
 '2024-07-13',
 '2024-07-14',
 '2024-07-17',
 '2024-07-18',
 '2024-07-19',
 '2024-07-20',
 '2024-07-21',
 '2024-07-23',
 '2024-07-25',
 '2024-07-26',
 '2024-07-27',
 '2024-07-30',
 '2024-08-04',
 '2024-08-05',
 '2024-08-06',
 '2024-08-08',
 '2024-08-10',
 '2024-08-11',
 '2024-08-13',
 '2024-08-14',
 '2024-08-19',
 '2024-08-20',
 '2024-08-21',
 '2024-08-22',
 '2024-08-23',
 '2024-08-24',
 '2024-08-25',
 '2024-08-27',
 '2024-08-28',
 '2024-08-29',
 '2024-08-30',
 '2024-09-01',
 '2024-09-02',
 '2024-09-04',
 '2024-09-06',
 '2024-09-08',
 '2024-09-10',
 '2024-09-14',
 '2024-09-15',
 '2024-09-16',
 '2024-09-17',
 '2024-09-19',
 '2024-09-20',
 '2024-09-21',
 '2024-09-22',
 '2024-09-23',
 '2024-09-24',
 '2024-09-25',
 '2024-09-28',
 '2024-09-29',
 '2024-09-30',
 '2024-10-01',
 '2024-10-02',
 '2024-10-03',
 '2024-10-04',
 '2024-10-05',
 '2024-10-06',
 '2024-10-10',
 '2024-10-12',
 '2024-10-14',
 '2024-10-15',
 '2024-10-17',
 '2024-10-18',
 '2024-10-19',
 '2024-10-20',
 '2024-10-21',
 '2024-10-22',
 '2024-10-23',
 '2024-10-24',
 '2024-10-26',
 '2024-10-27',
 '2024-10-28',
 '2024-10-30',
 '2024-10-31',
 '2024-11-01',
 '2024-11-02',
 '2024-11-03',
 '2024-11-05',
 '2024-11-06',
 '2024-11-07',
 '2024-11-08',
 '2024-11-09',
 '2024-11-10',
 '2024-11-11',
 '2024-11-13',
 '2024-11-15',
 '2024-11-20',
 '2024-11-21',
 '2024-11-22',
 '2024-11-23',
 '2024-11-24',
 '2024-11-25',
 '2024-11-27',
 '2024-11-28',
 '2024-12-01',
 '2024-12-02',
 '2024-12-03',
 '2024-12-04',
 '2024-12-05',
 '2024-12-06',
 '2024-12-07',
 '2024-12-08',
 '2024-12-10',
 '2024-12-13',
 '2024-12-14',
 '2024-12-15',
 '2024-12-16',
 '2024-12-17',
 '2024-12-18',
 '2024-12-19',
 '2024-12-21',
 '2024-12-23',
 '2024-12-26',
 '2024-12-27',
 '2024-12-28',
 '2024-12-29',
 '2024-12-30',
 '2024-12-31',
 '2025-01-01',
 '2025-01-02',
 '2025-01-03',
 '2025-01-04',
 '2025-01-05',
 '2025-01-06',
 '2025-01-07',
 '2025-01-08',
 '2025-01-09',
 '2025-01-10',
 '2025-01-11',
 '2025-01-12',
 '2025-01-13',
 '2025-01-15',
 '2025-01-18',
 '2025-01-19',
 '2025-01-20',
 '2025-01-21',
 '2025-01-23',
 '2025-01-26',
 '2025-01-29',
 '2025-02-01',
 '2025-02-02',
 '2025-02-07',
 '2025-02-08',
 '2025-02-09',
 '2025-02-10',
 '2025-02-12',
 '2025-02-14',
 '2025-02-15',
 '2025-02-16',
 '2025-02-18',
 '2025-02-20',
 '2025-02-21',
 '2025-02-22',
 '2025-02-23',
 '2025-02-24',
 '2025-02-25',
 '2025-02-27',
 '2025-02-28',
 '2025-03-01',
 '2025-03-02',
 '2025-03-03',
 '2025-03-04',
 '2025-03-05',
 '2025-03-06',
 '2025-03-07',
 '2025-03-08',
 '2025-03-09',
 '2025-03-10',
 '2025-03-11',
 '2025-03-12',
 '2025-03-13',
 '2025-03-14',
 '2025-03-15',
 '2025-03-16',
 '2025-03-17',
 '2025-03-19',
 '2025-03-20',
 '2025-03-21',
 '2025-03-22',
 '2025-03-23',
 '2025-03-24',
 '2025-03-25',
 '2025-03-26',
 '2025-03-27',
 '2025-03-28',
 '2025-03-29',
 '2025-03-31',
 '2025-04-01',
 '2025-04-02',
 '2025-04-03',
 '2025-04-04',
 '2025-04-08',
 '2025-04-09',
 '2025-04-10',
 '2025-04-11',
 '2025-04-12',
 '2025-04-14',
 '2025-04-15',
 '2025-04-18',
 '2025-04-19',
 '2025-04-20',
 '2025-04-22',
 '2025-04-25',
 '2025-04-26',
 '2025-04-27',
 '2025-04-30',
 '2025-05-02',
 '2025-05-03',
 '2025-05-04',
 '2025-05-05',
 '2025-05-06',
 '2025-05-07',
 '2025-05-08',
 '2025-05-09',
 '2025-05-10',
 '2025-05-11',
 '2025-05-12',
 '2025-05-14',
 '2025-05-15',
 '2025-05-16',
 '2025-05-17',
 '2025-05-18',
 '2025-05-19',
 '2025-05-20',
 '2025-05-21',
 '2025-05-22',
 '2025-05-24',
 '2025-05-25',
 '2025-05-26',
 '2025-05-27',
 '2025-05-29',
 '2025-05-30',
 '2025-05-31',
 '2025-06-01',
 '2025-06-02',
 '2025-06-03',
 '2025-06-04',
 '2025-06-05',
 '2025-06-06',
 '2025-06-07',
 '2025-06-08',
 '2025-06-09',
 '2025-06-10',
 '2025-06-14',
 '2025-06-15',
 '2025-06-16',
 '2025-06-17',
 '2025-06-18',
 '2025-06-19',
 '2025-06-20',
 '2025-06-21',
 '2025-06-22',
 '2025-06-23',
 '2025-06-24',
 '2025-06-25',
 '2025-06-26',
 '2025-06-29',
 '2025-06-30',
 '2025-07-01',
 '2025-07-02',
 '2025-07-03',
 '2025-07-05',
 '2025-07-06',
 '2025-07-07',
 '2025-07-09',
 '2025-07-10',
 '2025-07-13',
 '2025-07-17',
 '2025-07-19',
 '2025-07-20',
 '2025-07-22',
 '2025-07-24',
 '2025-07-25',
 '2025-07-26',
 '2025-07-27',
 '2025-07-30',
 '2025-08-01',
 '2025-08-02',
 '2025-08-04',
 '2025-08-05',
 '2025-08-06',
 '2025-08-07',
 '2025-08-08',
 '2025-08-09',
 '2025-08-10',
 '2025-08-11',
 '2025-08-13',
 '2025-08-14',
 '2025-08-16',
 '2025-08-17',
 '2025-08-19',
 '2025-08-23',
 '2025-08-24',
 '2025-08-25',
 '2025-08-26',
 '2025-08-29',
 '2025-08-30',
 '2025-08-31',
 '2025-09-03',
 '2025-09-04',
 '2025-09-05',
 '2025-09-06',
 '2025-09-07',
 '2025-09-08',
 '2025-09-09',
 '2025-09-10',
 '2025-09-14',
 '2025-09-16',
 '2025-09-18',
 '2025-09-19',
 '2025-09-21',
 '2025-09-22',
 '2025-09-23',
 '2025-09-24',
 '2025-09-25',
 '2025-09-26',
 '2025-09-27',
 '2025-09-28',
 '2025-10-01',
 '2025-10-02',
 '2025-10-04',
 '2025-10-05',
 '2025-10-06',
 '2025-10-09',
 '2025-10-12',
 '2025-10-15',
 '2025-10-16',
 '2025-10-18',
 '2025-10-19',
 '2025-10-20',
 '2025-10-22',
 '2025-10-23',
 '2025-10-24',
 '2025-10-25',
 '2025-10-26',
 '2025-10-29',
 '2025-11-05',
 '2025-11-07',
 '2025-11-08',
 '2025-11-09',
 '2025-11-10',
 '2025-11-11',
 '2025-11-12',
 '2025-11-14',
 '2025-11-15',
 '2025-11-16',
 '2025-11-17',
 '2025-11-18',
 '2025-11-20',
 '2025-11-21',
 '2025-11-23',
 '2025-11-29',
 '2025-11-30',
 '2025-12-02',
 '2025-12-04',
 '2025-12-05',
 '2025-12-06',
 '2025-12-07',
 '2025-12-08',
 '2025-12-09',
 '2025-12-10',
 '2025-12-11',
 '2025-12-12',
 '2025-12-14',
 '2025-12-15',
 '2025-12-16',
 '2025-12-17',
 '2025-12-20',
 '2025-12-21',
 '2025-12-23',
 '2025-12-24',
 '2025-12-25',
 '2025-12-26',
 '2025-12-27',
 '2025-12-28',
 '2025-12-29',
 '2025-12-31',
 '2026-01-03',
 '2026-01-05',
 '2026-01-07',
 '2026-01-09',
 '2026-01-14',
 '2026-01-17',
 '2026-01-22',
 '2026-01-24',
 '2026-01-25',
 '2026-01-26',
 '2026-01-31']

In [38]:
#verifico si dio bien  o cualquier cosa

In [47]:
data.loc[data.date.str.startswith('2026-01-26')]

Empty DataFrame
Columns: [Unnamed: 0, date, title, ma, axp, cof]
Index: []

In [ ]:
#despues de probar 10 veces, descubri que funciona bien, no hay noticias de esas fechas, asi que hay que salir a buscar.

In [2]:
from datetime import datetime, date
fecha_string = "2025-01-01"
objeto_fecha = date.fromisoformat(fecha_string)

In [3]:
fecha_string

'2025-01-01'