In [2]:
import pandas as pd

In [7]:
news_values = pd.read_csv('../data/csv/stock_values_from_2023-07-17_to_2026-03-04.csv')

In [2]:
import sys
import os

sys.path.append(os.path.abspath("../src"))

from steps.feature_engineering.invest_feature_pipe.feature_technical_agg import FeatureAgregation
from steps.feature_engineering.invest_feature_pipe.steps_pi import Ema_aggregation, Mma_agregation, Rsi_aggregation, Target_agregation

In [3]:
ema8 = Ema_aggregation(8)
ema21 = Ema_aggregation(21)
rsi14 = Rsi_aggregation(14)
mma200 = Mma_agregation(200)
target = Target_agregation(1)

In [4]:
pipe = FeatureAgregation()

In [8]:
pipe.add_feature(ema8)
pipe.add_feature(ema21)
pipe.add_feature(rsi14)
pipe.add_feature(mma200)
pipe.add_feature(target)

In [9]:
data = pipe.process(news_values)

In [10]:
news_values

,Date,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits,distance_ema_8,distance_ema_21,rsi_14,distance_mma_200,target
0,2023-07-17 00:00:00-04:00,401.950012,404.000000,401.119995,402.200012,396.431427,2344500,0.0,0.0,0.000000,0.000000,NaN,NaN,NaN
1,2023-07-18 00:00:00-04:00,400.420013,401.940002,395.209991,398.160004,392.449341,2676200,0.0,0.0,0.007830,0.009140,0.000000,NaN,0.000276
2,2023-07-19 00:00:00-04:00,398.000000,399.850006,396.309998,398.269989,392.557831,1809700,0.0,0.0,0.005887,0.008067,0.209135,NaN,-0.000527
3,2023-07-20 00:00:00-04:00,397.140015,399.720001,395.549988,398.059998,392.350800,2570700,0.0,0.0,0.004993,0.007815,0.208240,NaN,-0.001432
4,2023-07-21 00:00:00-04:00,398.670013,401.510010,397.420013,397.489990,391.788940,1868100,0.0,0.0,0.004999,0.008403,0.205667,NaN,0.018365
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
655,2026-02-25 00:00:00-05:00,502.820007,510.540009,502.420013,509.390015,509.390015,4139100,0.0,0.0,0.009651,0.033419,39.750885,0.092459,0.010562
656,2026-02-26 00:00:00-05:00,510.950012,519.900024,509.010010,514.770020,514.770020,4843600,0.0,0.0,-0.000629,0.021145,42.720325,0.082453,0.004740
657,2026-02-27 00:00:00-05:00,509.470001,518.760010,506.750000,517.210022,517.210022,5121100,0.0,0.0,-0.004173,0.015027,44.066762,0.077622,0.007328
658,2026-03-02 00:00:00-05:00,509.480011,526.159973,507.339996,521.000000,521.000000,3827000,0.0,0.0,-0.008946,0.007105,46.182867,0.070422,0.006372
659,2026-03-03 00:00:00-05:00,513.609985,526.799988,513.000000,524.320007,524.320007,4199700,0.0,0.0,-0.011918,0.000707,48.037444,0.064109,NaN

In [11]:
news_values.loc[199]

Date                2024-04-30 00:00:00-04:00
Open                                456.26001
High                               457.720001
Low                                450.880005
Close                              451.200012
Adj Close                          446.693146
Volume                                2698800
Dividends                                 0.0
Stock Splits                              0.0
distance_ema_8                       0.015983
distance_ema_21                      0.026082
rsi_14                              33.560973
distance_mma_200                     -0.06235
Name: 199, dtype: object

In [5]:
pipe.add_feature(target)

In [8]:
data = pipe.process(news_values)

In [9]:
data

,Date,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits,target
0,2023-07-17 00:00:00-04:00,401.950012,404.000000,401.119995,402.200012,396.431427,2344500,0.0,0.0,-0.010045
1,2023-07-18 00:00:00-04:00,400.420013,401.940002,395.209991,398.160004,392.449341,2676200,0.0,0.0,0.000276
2,2023-07-19 00:00:00-04:00,398.000000,399.850006,396.309998,398.269989,392.557831,1809700,0.0,0.0,-0.000527
3,2023-07-20 00:00:00-04:00,397.140015,399.720001,395.549988,398.059998,392.350800,2570700,0.0,0.0,-0.001432
4,2023-07-21 00:00:00-04:00,398.670013,401.510010,397.420013,397.489990,391.788940,1868100,0.0,0.0,0.018365
...,...,...,...,...,...,...,...,...,...,...
655,2026-02-25 00:00:00-05:00,502.820007,510.540009,502.420013,509.390015,509.390015,4139100,0.0,0.0,0.010562
656,2026-02-26 00:00:00-05:00,510.950012,519.900024,509.010010,514.770020,514.770020,4843600,0.0,0.0,0.004740
657,2026-02-27 00:00:00-05:00,509.470001,518.760010,506.750000,517.210022,517.210022,5121100,0.0,0.0,0.007328
658,2026-03-02 00:00:00-05:00,509.480011,526.159973,507.339996,521.000000,521.000000,3827000,0.0,0.0,0.006372
659,2026-03-03 00:00:00-05:00,513.609985,526.799988,513.000000,524.320007,524.320007,4199700,0.0,0.0,NaN

In [3]:
data = pd.read_csv('../data/csv/final.csv')

In [4]:
data

,Volume,ma,axp,cof,news_score,distance_ema_8,distance_ema_21,distance_mma_200,target,has_news
0,3961700,0.0,0.0,0.0,0.0,0.000006,-0.000450,-0.072180,0.004058,0
1,2301300,0.0,0.0,0.0,0.0,-0.003148,-0.004097,-0.075723,0.004413,0
2,1933300,0.0,0.0,0.0,0.0,-0.005882,-0.007747,-0.079594,0.005320,0
3,3739700,0.0,0.0,0.0,0.0,-0.008715,-0.011903,-0.084450,-0.006293,0
4,3327800,0.0,0.0,0.0,0.0,-0.001841,-0.005030,-0.076852,0.011579,0
...,...,...,...,...,...,...,...,...,...,...
672,5292900,0.0,0.0,0.0,0.0,0.034458,0.058179,0.113189,0.022872,0
673,4139100,0.0,0.0,0.0,0.0,0.009651,0.033419,0.092459,0.010562,0
674,4843600,0.0,0.0,0.0,0.0,-0.000629,0.021145,0.082453,0.004740,0
675,5121100,0.0,1.0,0.0,0.0,-0.004173,0.015027,0.077622,0.007328,1
676,3827000,0.0,0.0,0.0,0.0,-0.008946,0.007105,0.070422,0.006372,0

In [6]:
data.loc[data.news_score != 0]

,Volume,ma,axp,cof,news_score,distance_ema_8,distance_ema_21,distance_mma_200,target,has_news
18,2344500,0.0,0.0,0.0,0.179513,-0.010930,-0.030807,-0.130712,-0.010045,1
19,2676200,0.0,0.0,0.0,0.613497,-0.000603,-0.018559,-0.117629,0.000276,1
20,1809700,0.0,0.0,0.0,0.037092,-0.000684,-0.017098,-0.116163,-0.000527,1
23,3029800,0.0,0.0,0.0,0.415975,-0.013425,-0.028032,-0.129219,-0.008671,1
25,2572300,0.0,0.0,0.0,0.318649,-0.004993,-0.018343,-0.119402,-0.019657,1
...,...,...,...,...,...,...,...,...,...,...
659,4448000,1.0,0.0,0.0,0.913941,-0.017133,-0.014146,0.015818,-0.002945,1
665,3466200,1.0,1.0,0.0,0.677594,0.020920,0.028346,0.062857,-0.017253,1
667,3178000,0.0,0.0,0.5,0.012178,0.017961,0.031530,0.072328,0.011592,1
668,3575900,0.5,0.0,0.0,0.090666,0.005124,0.018492,0.061438,-0.014622,1
671,6312300,1.0,0.0,0.0,0.754209,0.047653,0.067331,0.117216,0.003972,1