In [70]:
import requests
import os

In [71]:
import pandas as pd

In [72]:
from dotenv import load_dotenv

In [73]:
load_dotenv()

True

In [74]:
mastercard_ticker = "MA"
api_key = os.getenv("API_KEY")

In [75]:
config_data = {
    "ticker": "MA",
    "published_utc_start": "2024-02-05",
    "published_utc_end": "2026-02-08",
    "sort": "published_utc",
    "limit":"950",
    "apiKey":api_key
}

In [76]:
try:
    data = requests.get("https://api.massive.com/v2/reference/news", params=config_data)
except Exception as e:
    print(f"no funciono bro, paso esto: {e}")

In [77]:
prueba  = data.json()

In [ ]:
prueba["results"]

{'id': '87ecc96733f7e8f033b1ddea17efad30a1c2480248b9d7a5f6824e5925927c84',
 'publisher': {'name': 'GlobeNewswire Inc.',
  'homepage_url': 'https://www.globenewswire.com',
  'logo_url': 'https://s3.massive.com/public/assets/news/logos/globenewswire.svg',
  'favicon_url': 'https://s3.massive.com/public/assets/news/favicons/globenewswire.ico'},
 'title': 'Bitget propose l’achat automatique pour permettre l’investissement passif avec un rendement annuel pouvant atteindre 30\xa0%',
 'author': 'Victoria, Seychelles',
 'published_utc': '2025-08-03T19:04:00Z',
 'article_url': 'https://www.globenewswire.com/news-release/2025/08/03/3126249/0/fr/Bitget-propose-l-achat-automatique-pour-permettre-l-investissement-passif-avec-un-rendement-annuel-pouvant-atteindre-30.html',
 'tickers': ['V', 'MA'],
 'image_url': 'https://ml-eu.globenewswire.com/Resource/Download/1d6d5ad9-e478-4b92-a907-c63f166a3af9',
 'description': 'Bitget introduces a new Recurring Buy feature allowing users to automatically purchase cryptocurrencies like Bitcoin and Ethereum using Visa/Mastercard, implementing a Dollar Cost Averaging strategy with potential annual returns up to 30%.',
 'keywords': ['cryptocurrency',
  'passive investing',
  'Dollar Cost Averaging',
  'Bitcoin',
  'Ethereum',
  'automated investing'],
 'insights': [{'ticker': 'V',
   'sentiment': 'neutral',
   'sentiment_reasoning': 'Mentioned as a payment method for the new investment feature'},
  {'ticker': 'MA',
   'sentiment': 'neutral',
   'sentiment_reasoning': 'Mentioned as a payment method for the new investment feature'}]}

In [ ]:
ver_noticias = [notice for notice in prueba["results"] if "description" in list(notice.keys())]

In [86]:
len(ver_noticias)

941

In [87]:
len(prueba["results"])

950

In [89]:
important_data = []
for news in data.json()["results"]:
    if "description" in list(news.keys()):
        new_dict = {}
        new_dict["date"] = news["published_utc"]
        new_dict["title"] = news["title"]
        new_dict["real_news"] = news["description"]
        new_dict["ma"] = None
        new_dict["axp"] = None
        new_dict["cof"] = None
        if "insights" in news:
            top3_important_tickers(news["insights"],new_dict)
        important_data.append(new_dict)

In [88]:
def top3_important_tickers(sentiments, dic):
    count=0
    for ticker in sentiments:
        match ticker["ticker"]:
            case "MA":
                dic["ma"] = ticker["sentiment"]
                count += 1
            case "AXP":
                dic["axp"] = ticker["sentiment"]
                count += 1
            case "COF":
                dic["cof"] = ticker["sentiment"]
                count += 1
            case _:
                pass
                
        if count == 3:
            break 
    return dic

In [92]:
data_frame_data = pd.DataFrame(important_data)

In [93]:
data_frame_data

,date,title,real_news,ma,axp,cof
0,2026-02-08T15:05:00Z,Visa and Mastercard Execs Recently Dismissed S...,Visa and Mastercard executives have dismissed ...,negative,None,None
1,2026-02-04T18:42:00Z,Behavioral Biometrics Market to Reach US$ 18.3...,The global behavioral biometrics market is pro...,positive,None,None
2,2026-02-03T21:15:00Z,Here's Why Mastercard Stock Is Still a Buy Des...,Despite regulatory headwinds from a proposed 1...,positive,negative,negative
3,2026-02-02T10:05:23Z,Why a 2.1% Portfolio Shift Targets a New ETF W...,Capital Planning LLC initiated a new position ...,positive,None,None
4,2026-02-01T22:01:11Z,Affiance Financial Bets $43 Million on Chuck A...,Affiance Financial initiated a new $43 million...,positive,None,None
...,...,...,...,...,...,...
936,2023-07-13T15:40:11Z,FIS or MA: Which Is the Better Value Stock Rig...,FIS vs. MA: Which Stock Is the Better Value Op...,None,None,None
937,2023-07-13T11:59:22Z,Netflix To Rally More Than 11%? Here Are 10 Ot...,Mizuho boosted the price target for Gulfport ...,None,None,None
938,2023-07-13T09:15:00Z,1 Spectacular Warren Buffett Dividend Stock Th...,Warren Buffett is not against investing in div...,None,None,None
939,2023-07-11T21:50:20Z,MasterCard (MA) Outpaces Stock Market Gains: W...,"In the latest trading session, MasterCard (MA)...",None,None,None
940,2023-07-11T14:53:00Z,Mastercard (MA) & JazzCash to Speed Up Digitiz...,Mastercard (MA) partners with JazzCash to driv...,None,None,None

In [94]:
data_frame_data.sort_values(by="date",ascending=True)

,date,title,real_news,ma,axp,cof
940,2023-07-11T14:53:00Z,Mastercard (MA) & JazzCash to Speed Up Digitiz...,Mastercard (MA) partners with JazzCash to driv...,None,None,None
939,2023-07-11T21:50:20Z,MasterCard (MA) Outpaces Stock Market Gains: W...,"In the latest trading session, MasterCard (MA)...",None,None,None
938,2023-07-13T09:15:00Z,1 Spectacular Warren Buffett Dividend Stock Th...,Warren Buffett is not against investing in div...,None,None,None
937,2023-07-13T11:59:22Z,Netflix To Rally More Than 11%? Here Are 10 Ot...,Mizuho boosted the price target for Gulfport ...,None,None,None
936,2023-07-13T15:40:11Z,FIS or MA: Which Is the Better Value Stock Rig...,FIS vs. MA: Which Stock Is the Better Value Op...,None,None,None
...,...,...,...,...,...,...
4,2026-02-01T22:01:11Z,Affiance Financial Bets $43 Million on Chuck A...,Affiance Financial initiated a new $43 million...,positive,None,None
3,2026-02-02T10:05:23Z,Why a 2.1% Portfolio Shift Targets a New ETF W...,Capital Planning LLC initiated a new position ...,positive,None,None
2,2026-02-03T21:15:00Z,Here's Why Mastercard Stock Is Still a Buy Des...,Despite regulatory headwinds from a proposed 1...,positive,negative,negative
1,2026-02-04T18:42:00Z,Behavioral Biometrics Market to Reach US$ 18.3...,The global behavioral biometrics market is pro...,positive,None,None
0,2026-02-08T15:05:00Z,Visa and Mastercard Execs Recently Dismissed S...,Visa and Mastercard executives have dismissed ...,negative,None,None

In [95]:
from datetime import datetime

In [96]:
date_nueva = [datetime.fromisoformat(date[:10]) for date in data_frame_data.date]

In [97]:
date_nueva

[datetime.datetime(2026, 2, 8, 0, 0),
 datetime.datetime(2026, 2, 4, 0, 0),
 datetime.datetime(2026, 2, 3, 0, 0),
 datetime.datetime(2026, 2, 2, 0, 0),
 datetime.datetime(2026, 2, 1, 0, 0),
 datetime.datetime(2026, 2, 1, 0, 0),
 datetime.datetime(2026, 1, 30, 0, 0),
 datetime.datetime(2026, 1, 29, 0, 0),
 datetime.datetime(2026, 1, 28, 0, 0),
 datetime.datetime(2026, 1, 28, 0, 0),
 datetime.datetime(2026, 1, 27, 0, 0),
 datetime.datetime(2026, 1, 23, 0, 0),
 datetime.datetime(2026, 1, 21, 0, 0),
 datetime.datetime(2026, 1, 20, 0, 0),
 datetime.datetime(2026, 1, 19, 0, 0),
 datetime.datetime(2026, 1, 18, 0, 0),
 datetime.datetime(2026, 1, 16, 0, 0),
 datetime.datetime(2026, 1, 15, 0, 0),
 datetime.datetime(2026, 1, 13, 0, 0),
 datetime.datetime(2026, 1, 12, 0, 0),
 datetime.datetime(2026, 1, 11, 0, 0),
 datetime.datetime(2026, 1, 10, 0, 0),
 datetime.datetime(2026, 1, 8, 0, 0),
 datetime.datetime(2026, 1, 6, 0, 0),
 datetime.datetime(2026, 1, 6, 0, 0),
 datetime.datetime(2026, 1, 6, 0, 0),
 datetime.datetime(2026, 1, 4, 0, 0),
 datetime.datetime(2026, 1, 2, 0, 0),
 datetime.datetime(2026, 1, 1, 0, 0),
 datetime.datetime(2025, 12, 30, 0, 0),
 datetime.datetime(2025, 12, 22, 0, 0),
 datetime.datetime(2025, 12, 19, 0, 0),
 datetime.datetime(2025, 12, 18, 0, 0),
 datetime.datetime(2025, 12, 18, 0, 0),
 datetime.datetime(2025, 12, 18, 0, 0),
 datetime.datetime(2025, 12, 13, 0, 0),
 datetime.datetime(2025, 12, 3, 0, 0),
 datetime.datetime(2025, 12, 1, 0, 0),
 datetime.datetime(2025, 12, 1, 0, 0),
 datetime.datetime(2025, 11, 28, 0, 0),
 datetime.datetime(2025, 11, 27, 0, 0),
 datetime.datetime(2025, 11, 26, 0, 0),
 datetime.datetime(2025, 11, 25, 0, 0),
 datetime.datetime(2025, 11, 24, 0, 0),
 datetime.datetime(2025, 11, 22, 0, 0),
 datetime.datetime(2025, 11, 19, 0, 0),
 datetime.datetime(2025, 11, 13, 0, 0),
 datetime.datetime(2025, 11, 6, 0, 0),
 datetime.datetime(2025, 11, 4, 0, 0),
 datetime.datetime(2025, 11, 3, 0, 0),
 datetime.datetime(2025, 11, 3, 0, 0),
 datetime.datetime(2025, 11, 2, 0, 0),
 datetime.datetime(2025, 11, 1, 0, 0),
 datetime.datetime(2025, 11, 1, 0, 0),
 datetime.datetime(2025, 10, 31, 0, 0),
 datetime.datetime(2025, 10, 30, 0, 0),
 datetime.datetime(2025, 10, 28, 0, 0),
 datetime.datetime(2025, 10, 27, 0, 0),
 datetime.datetime(2025, 10, 21, 0, 0),
 datetime.datetime(2025, 10, 21, 0, 0),
 datetime.datetime(2025, 10, 21, 0, 0),
 datetime.datetime(2025, 10, 17, 0, 0),
 datetime.datetime(2025, 10, 14, 0, 0),
 datetime.datetime(2025, 10, 13, 0, 0),
 datetime.datetime(2025, 10, 11, 0, 0),
 datetime.datetime(2025, 10, 10, 0, 0),
 datetime.datetime(2025, 10, 8, 0, 0),
 datetime.datetime(2025, 10, 7, 0, 0),
 datetime.datetime(2025, 10, 7, 0, 0),
 datetime.datetime(2025, 10, 3, 0, 0),
 datetime.datetime(2025, 10, 3, 0, 0),
 datetime.datetime(2025, 9, 30, 0, 0),
 datetime.datetime(2025, 9, 29, 0, 0),
 datetime.datetime(2025, 9, 20, 0, 0),
 datetime.datetime(2025, 9, 17, 0, 0),
 datetime.datetime(2025, 9, 15, 0, 0),
 datetime.datetime(2025, 9, 13, 0, 0),
 datetime.datetime(2025, 9, 12, 0, 0),
 datetime.datetime(2025, 9, 11, 0, 0),
 datetime.datetime(2025, 9, 11, 0, 0),
 datetime.datetime(2025, 9, 11, 0, 0),
 datetime.datetime(2025, 9, 11, 0, 0),
 datetime.datetime(2025, 9, 11, 0, 0),
 datetime.datetime(2025, 9, 11, 0, 0),
 datetime.datetime(2025, 9, 2, 0, 0),
 datetime.datetime(2025, 9, 2, 0, 0),
 datetime.datetime(2025, 9, 1, 0, 0),
 datetime.datetime(2025, 8, 28, 0, 0),
 datetime.datetime(2025, 8, 28, 0, 0),
 datetime.datetime(2025, 8, 27, 0, 0),
 datetime.datetime(2025, 8, 22, 0, 0),
 datetime.datetime(2025, 8, 21, 0, 0),
 datetime.datetime(2025, 8, 20, 0, 0),
 datetime.datetime(2025, 8, 20, 0, 0),
 datetime.datetime(2025, 8, 18, 0, 0),
 datetime.datetime(2025, 8, 18, 0, 0),
 datetime.datetime(2025, 8, 18, 0, 0),
 datetime.datetime(2025, 8, 15, 0, 0),
 datetime.datetime(2025, 8, 12, 0, 0),
 datetime.datetime(2025, 8, 3, 0, 0),
 datetime.datetime(2025, 8, 3, 0, 0),
 datetime.datetime(2025, 8, 3, 0, 0),
 datetime.datetime(2025, 8, 3, 0, 0),
 datetime.datetime(2025, 8, 3, 0, 0),
 datetime.datetime(2025, 8, 3, 0, 0),
 datetime.datetime(2025, 8, 3, 0, 0),
 datetime.datetime(2025, 7, 31, 0, 0),
 datetime.datetime(2025, 7, 29, 0, 0),
 datetime.datetime(2025, 7, 28, 0, 0),
 datetime.datetime(2025, 7, 23, 0, 0),
 datetime.datetime(2025, 7, 21, 0, 0),
 datetime.datetime(2025, 7, 21, 0, 0),
 datetime.datetime(2025, 7, 21, 0, 0),
 datetime.datetime(2025, 7, 21, 0, 0),
 datetime.datetime(2025, 7, 18, 0, 0),
 datetime.datetime(2025, 7, 16, 0, 0),
 datetime.datetime(2025, 7, 15, 0, 0),
 datetime.datetime(2025, 7, 14, 0, 0),
 datetime.datetime(2025, 7, 12, 0, 0),
 datetime.datetime(2025, 7, 11, 0, 0),
 datetime.datetime(2025, 7, 8, 0, 0),
 datetime.datetime(2025, 7, 8, 0, 0),
 datetime.datetime(2025, 7, 8, 0, 0),
 datetime.datetime(2025, 7, 8, 0, 0),
 datetime.datetime(2025, 7, 8, 0, 0),
 datetime.datetime(2025, 7, 8, 0, 0),
 datetime.datetime(2025, 7, 8, 0, 0),
 datetime.datetime(2025, 7, 8, 0, 0),
 datetime.datetime(2025, 7, 4, 0, 0),
 datetime.datetime(2025, 6, 28, 0, 0),
 datetime.datetime(2025, 6, 27, 0, 0),
 datetime.datetime(2025, 6, 13, 0, 0),
 datetime.datetime(2025, 6, 12, 0, 0),
 datetime.datetime(2025, 6, 11, 0, 0),
 datetime.datetime(2025, 6, 11, 0, 0),
 datetime.datetime(2025, 5, 28, 0, 0),
 datetime.datetime(2025, 5, 28, 0, 0),
 datetime.datetime(2025, 5, 23, 0, 0),
 datetime.datetime(2025, 5, 13, 0, 0),
 datetime.datetime(2025, 5, 1, 0, 0),
 datetime.datetime(2025, 4, 29, 0, 0),
 datetime.datetime(2025, 4, 28, 0, 0),
 datetime.datetime(2025, 4, 24, 0, 0),
 datetime.datetime(2025, 4, 24, 0, 0),
 datetime.datetime(2025, 4, 23, 0, 0),
 datetime.datetime(2025, 4, 21, 0, 0),
 datetime.datetime(2025, 4, 21, 0, 0),
 datetime.datetime(2025, 4, 17, 0, 0),
 datetime.datetime(2025, 4, 16, 0, 0),
 datetime.datetime(2025, 4, 13, 0, 0),
 datetime.datetime(2025, 4, 7, 0, 0),
 datetime.datetime(2025, 4, 7, 0, 0),
 datetime.datetime(2025, 4, 6, 0, 0),
 datetime.datetime(2025, 4, 5, 0, 0),
 datetime.datetime(2025, 4, 5, 0, 0),
 datetime.datetime(2025, 3, 30, 0, 0),
 datetime.datetime(2025, 3, 18, 0, 0),
 datetime.datetime(2025, 2, 26, 0, 0),
 datetime.datetime(2025, 2, 19, 0, 0),
 datetime.datetime(2025, 2, 19, 0, 0),
 datetime.datetime(2025, 2, 17, 0, 0),
 datetime.datetime(2025, 2, 17, 0, 0),
 datetime.datetime(2025, 2, 13, 0, 0),
 datetime.datetime(2025, 2, 11, 0, 0),
 datetime.datetime(2025, 2, 6, 0, 0),
 datetime.datetime(2025, 2, 6, 0, 0),
 datetime.datetime(2025, 2, 6, 0, 0),
 datetime.datetime(2025, 2, 5, 0, 0),
 datetime.datetime(2025, 2, 4, 0, 0),
 datetime.datetime(2025, 2, 3, 0, 0),
 datetime.datetime(2025, 1, 31, 0, 0),
 datetime.datetime(2025, 1, 30, 0, 0),
 datetime.datetime(2025, 1, 28, 0, 0),
 datetime.datetime(2025, 1, 27, 0, 0),
 datetime.datetime(2025, 1, 25, 0, 0),
 datetime.datetime(2025, 1, 24, 0, 0),
 datetime.datetime(2025, 1, 22, 0, 0),
 datetime.datetime(2025, 1, 17, 0, 0),
 datetime.datetime(2025, 1, 16, 0, 0),
 datetime.datetime(2025, 1, 14, 0, 0),
 datetime.datetime(2024, 12, 25, 0, 0),
 datetime.datetime(2024, 12, 24, 0, 0),
 datetime.datetime(2024, 12, 24, 0, 0),
 datetime.datetime(2024, 12, 22, 0, 0),
 datetime.datetime(2024, 12, 20, 0, 0),
 datetime.datetime(2024, 12, 20, 0, 0),
 datetime.datetime(2024, 12, 12, 0, 0),
 datetime.datetime(2024, 12, 11, 0, 0),
 datetime.datetime(2024, 12, 9, 0, 0),
 datetime.datetime(2024, 11, 30, 0, 0),
 datetime.datetime(2024, 11, 29, 0, 0),
 datetime.datetime(2024, 11, 26, 0, 0),
 datetime.datetime(2024, 11, 19, 0, 0),
 datetime.datetime(2024, 11, 18, 0, 0),
 datetime.datetime(2024, 11, 18, 0, 0),
 datetime.datetime(2024, 11, 17, 0, 0),
 datetime.datetime(2024, 11, 16, 0, 0),
 datetime.datetime(2024, 11, 14, 0, 0),
 datetime.datetime(2024, 11, 12, 0, 0),
 datetime.datetime(2024, 11, 4, 0, 0),
 datetime.datetime(2024, 10, 29, 0, 0),
 datetime.datetime(2024, 10, 25, 0, 0),
 datetime.datetime(2024, 10, 16, 0, 0),
 datetime.datetime(2024, 10, 16, 0, 0),
 datetime.datetime(2024, 10, 13, 0, 0),
 datetime.datetime(2024, 10, 11, 0, 0),
 datetime.datetime(2024, 10, 9, 0, 0),
 datetime.datetime(2024, 10, 8, 0, 0),
 datetime.datetime(2024, 10, 7, 0, 0),
 datetime.datetime(2024, 9, 27, 0, 0),
 datetime.datetime(2024, 9, 26, 0, 0),
 datetime.datetime(2024, 9, 18, 0, 0),
 datetime.datetime(2024, 9, 18, 0, 0),
 datetime.datetime(2024, 9, 13, 0, 0),
 datetime.datetime(2024, 9, 12, 0, 0),
 datetime.datetime(2024, 9, 11, 0, 0),
 datetime.datetime(2024, 9, 9, 0, 0),
 datetime.datetime(2024, 9, 9, 0, 0),
 datetime.datetime(2024, 9, 7, 0, 0),
 datetime.datetime(2024, 9, 5, 0, 0),
 datetime.datetime(2024, 9, 3, 0, 0),
 datetime.datetime(2024, 9, 3, 0, 0),
 datetime.datetime(2024, 8, 31, 0, 0),
 datetime.datetime(2024, 8, 26, 0, 0),
 datetime.datetime(2024, 8, 18, 0, 0),
 datetime.datetime(2024, 8, 17, 0, 0),
 datetime.datetime(2024, 8, 16, 0, 0),
 datetime.datetime(2024, 8, 15, 0, 0),
 datetime.datetime(2024, 8, 15, 0, 0),
 datetime.datetime(2024, 8, 15, 0, 0),
 datetime.datetime(2024, 8, 12, 0, 0),
 datetime.datetime(2024, 8, 12, 0, 0),
 datetime.datetime(2024, 8, 9, 0, 0),
 datetime.datetime(2024, 8, 7, 0, 0),
 datetime.datetime(2024, 8, 3, 0, 0),
 datetime.datetime(2024, 8, 2, 0, 0),
 datetime.datetime(2024, 8, 2, 0, 0),
 datetime.datetime(2024, 8, 1, 0, 0),
 datetime.datetime(2024, 7, 31, 0, 0),
 datetime.datetime(2024, 7, 31, 0, 0),
 datetime.datetime(2024, 7, 29, 0, 0),
 datetime.datetime(2024, 7, 28, 0, 0),
 datetime.datetime(2024, 7, 24, 0, 0),
 datetime.datetime(2024, 7, 22, 0, 0),
 datetime.datetime(2024, 7, 22, 0, 0),
 datetime.datetime(2024, 7, 22, 0, 0),
 datetime.datetime(2024, 7, 22, 0, 0),
 datetime.datetime(2024, 7, 16, 0, 0),
 datetime.datetime(2024, 7, 15, 0, 0),
 datetime.datetime(2024, 7, 12, 0, 0),
 datetime.datetime(2024, 7, 10, 0, 0),
 datetime.datetime(2024, 7, 10, 0, 0),
 datetime.datetime(2024, 7, 9, 0, 0),
 datetime.datetime(2024, 7, 8, 0, 0),
 datetime.datetime(2024, 7, 5, 0, 0),
 datetime.datetime(2024, 7, 5, 0, 0),
 datetime.datetime(2024, 7, 4, 0, 0),
 datetime.datetime(2024, 7, 3, 0, 0),
 datetime.datetime(2024, 7, 1, 0, 0),
 datetime.datetime(2024, 7, 1, 0, 0),
 datetime.datetime(2024, 7, 1, 0, 0),
 datetime.datetime(2024, 6, 29, 0, 0),
 datetime.datetime(2024, 6, 28, 0, 0),
 datetime.datetime(2024, 6, 28, 0, 0),
 datetime.datetime(2024, 6, 27, 0, 0),
 datetime.datetime(2024, 6, 27, 0, 0),
 datetime.datetime(2024, 6, 27, 0, 0),
 datetime.datetime(2024, 6, 27, 0, 0),
 datetime.datetime(2024, 6, 26, 0, 0),
 datetime.datetime(2024, 6, 26, 0, 0),
 datetime.datetime(2024, 6, 25, 0, 0),
 datetime.datetime(2024, 6, 25, 0, 0),
 datetime.datetime(2024, 6, 24, 0, 0),
 datetime.datetime(2024, 6, 24, 0, 0),
 datetime.datetime(2024, 6, 22, 0, 0),
 datetime.datetime(2024, 6, 22, 0, 0),
 datetime.datetime(2024, 6, 22, 0, 0),
 datetime.datetime(2024, 6, 20, 0, 0),
 datetime.datetime(2024, 6, 20, 0, 0),
 datetime.datetime(2024, 6, 20, 0, 0),
 datetime.datetime(2024, 6, 19, 0, 0),
 datetime.datetime(2024, 6, 18, 0, 0),
 datetime.datetime(2024, 6, 18, 0, 0),
 datetime.datetime(2024, 6, 14, 0, 0),
 datetime.datetime(2024, 6, 12, 0, 0),
 datetime.datetime(2024, 6, 12, 0, 0),
 datetime.datetime(2024, 6, 12, 0, 0),
 datetime.datetime(2024, 6, 12, 0, 0),
 datetime.datetime(2024, 6, 10, 0, 0),
 datetime.datetime(2024, 6, 10, 0, 0),
 datetime.datetime(2024, 6, 7, 0, 0),
 datetime.datetime(2024, 6, 6, 0, 0),
 datetime.datetime(2024, 6, 6, 0, 0),
 datetime.datetime(2024, 6, 6, 0, 0),
 datetime.datetime(2024, 6, 6, 0, 0),
 datetime.datetime(2024, 6, 6, 0, 0),
 datetime.datetime(2024, 6, 5, 0, 0),
 datetime.datetime(2024, 6, 4, 0, 0),
 datetime.datetime(2024, 6, 4, 0, 0),
 datetime.datetime(2024, 6, 3, 0, 0),
 datetime.datetime(2024, 6, 3, 0, 0),
 datetime.datetime(2024, 6, 2, 0, 0),
 datetime.datetime(2024, 5, 31, 0, 0),
 datetime.datetime(2024, 5, 31, 0, 0),
 datetime.datetime(2024, 5, 31, 0, 0),
 datetime.datetime(2024, 5, 31, 0, 0),
 datetime.datetime(2024, 5, 31, 0, 0),
 datetime.datetime(2024, 5, 30, 0, 0),
 datetime.datetime(2024, 5, 29, 0, 0),
 datetime.datetime(2024, 5, 28, 0, 0),
 datetime.datetime(2024, 5, 27, 0, 0),
 datetime.datetime(2024, 5, 24, 0, 0),
 datetime.datetime(2024, 5, 24, 0, 0),
 datetime.datetime(2024, 5, 23, 0, 0),
 datetime.datetime(2024, 5, 23, 0, 0),
 datetime.datetime(2024, 5, 23, 0, 0),
 datetime.datetime(2024, 5, 22, 0, 0),
 datetime.datetime(2024, 5, 22, 0, 0),
 datetime.datetime(2024, 5, 21, 0, 0),
 datetime.datetime(2024, 5, 20, 0, 0),
 datetime.datetime(2024, 5, 20, 0, 0),
 datetime.datetime(2024, 5, 17, 0, 0),
 datetime.datetime(2024, 5, 17, 0, 0),
 datetime.datetime(2024, 5, 17, 0, 0),
 datetime.datetime(2024, 5, 16, 0, 0),
 datetime.datetime(2024, 5, 16, 0, 0),
 datetime.datetime(2024, 5, 15, 0, 0),
 datetime.datetime(2024, 5, 15, 0, 0),
 datetime.datetime(2024, 5, 13, 0, 0),
 datetime.datetime(2024, 5, 13, 0, 0),
 datetime.datetime(2024, 5, 13, 0, 0),
 datetime.datetime(2024, 5, 13, 0, 0),
 datetime.datetime(2024, 5, 12, 0, 0),
 datetime.datetime(2024, 5, 12, 0, 0),
 datetime.datetime(2024, 5, 12, 0, 0),
 datetime.datetime(2024, 5, 10, 0, 0),
 datetime.datetime(2024, 5, 10, 0, 0),
 datetime.datetime(2024, 5, 9, 0, 0),
 datetime.datetime(2024, 5, 9, 0, 0),
 datetime.datetime(2024, 5, 9, 0, 0),
 datetime.datetime(2024, 5, 8, 0, 0),
 datetime.datetime(2024, 5, 7, 0, 0),
 datetime.datetime(2024, 5, 6, 0, 0),
 datetime.datetime(2024, 5, 6, 0, 0),
 datetime.datetime(2024, 5, 4, 0, 0),
 datetime.datetime(2024, 5, 3, 0, 0),
 datetime.datetime(2024, 5, 3, 0, 0),
 datetime.datetime(2024, 5, 2, 0, 0),
 datetime.datetime(2024, 5, 2, 0, 0),
 datetime.datetime(2024, 5, 2, 0, 0),
 datetime.datetime(2024, 5, 1, 0, 0),
 datetime.datetime(2024, 5, 1, 0, 0),
 datetime.datetime(2024, 5, 1, 0, 0),
 datetime.datetime(2024, 5, 1, 0, 0),
 datetime.datetime(2024, 5, 1, 0, 0),
 datetime.datetime(2024, 5, 1, 0, 0),
 datetime.datetime(2024, 5, 1, 0, 0),
 datetime.datetime(2024, 5, 1, 0, 0),
 datetime.datetime(2024, 4, 30, 0, 0),
 datetime.datetime(2024, 4, 30, 0, 0),
 datetime.datetime(2024, 4, 29, 0, 0),
 datetime.datetime(2024, 4, 29, 0, 0),
 datetime.datetime(2024, 4, 28, 0, 0),
 datetime.datetime(2024, 4, 28, 0, 0),
 datetime.datetime(2024, 4, 28, 0, 0),
 datetime.datetime(2024, 4, 27, 0, 0),
 datetime.datetime(2024, 4, 27, 0, 0),
 datetime.datetime(2024, 4, 26, 0, 0),
 datetime.datetime(2024, 4, 26, 0, 0),
 datetime.datetime(2024, 4, 26, 0, 0),
 datetime.datetime(2024, 4, 26, 0, 0),
 datetime.datetime(2024, 4, 25, 0, 0),
 datetime.datetime(2024, 4, 25, 0, 0),
 datetime.datetime(2024, 4, 24, 0, 0),
 datetime.datetime(2024, 4, 24, 0, 0),
 datetime.datetime(2024, 4, 22, 0, 0),
 datetime.datetime(2024, 4, 22, 0, 0),
 datetime.datetime(2024, 4, 22, 0, 0),
 datetime.datetime(2024, 4, 19, 0, 0),
 datetime.datetime(2024, 4, 19, 0, 0),
 datetime.datetime(2024, 4, 18, 0, 0),
 datetime.datetime(2024, 4, 18, 0, 0),
 datetime.datetime(2024, 4, 17, 0, 0),
 datetime.datetime(2024, 4, 17, 0, 0),
 datetime.datetime(2024, 4, 17, 0, 0),
 datetime.datetime(2024, 4, 17, 0, 0),
 datetime.datetime(2024, 4, 16, 0, 0),
 datetime.datetime(2024, 4, 16, 0, 0),
 datetime.datetime(2024, 4, 16, 0, 0),
 datetime.datetime(2024, 4, 16, 0, 0),
 datetime.datetime(2024, 4, 15, 0, 0),
 datetime.datetime(2024, 4, 12, 0, 0),
 datetime.datetime(2024, 4, 12, 0, 0),
 datetime.datetime(2024, 4, 12, 0, 0),
 datetime.datetime(2024, 4, 11, 0, 0),
 datetime.datetime(2024, 4, 11, 0, 0),
 datetime.datetime(2024, 4, 10, 0, 0),
 datetime.datetime(2024, 4, 10, 0, 0),
 datetime.datetime(2024, 4, 10, 0, 0),
 datetime.datetime(2024, 4, 9, 0, 0),
 datetime.datetime(2024, 4, 7, 0, 0),
 datetime.datetime(2024, 4, 6, 0, 0),
 datetime.datetime(2024, 4, 6, 0, 0),
 datetime.datetime(2024, 4, 5, 0, 0),
 datetime.datetime(2024, 4, 5, 0, 0),
 datetime.datetime(2024, 4, 4, 0, 0),
 datetime.datetime(2024, 4, 4, 0, 0),
 datetime.datetime(2024, 4, 3, 0, 0),
 datetime.datetime(2024, 4, 2, 0, 0),
 datetime.datetime(2024, 4, 1, 0, 0),
 datetime.datetime(2024, 3, 31, 0, 0),
 datetime.datetime(2024, 3, 31, 0, 0),
 datetime.datetime(2024, 3, 31, 0, 0),
 datetime.datetime(2024, 3, 30, 0, 0),
 datetime.datetime(2024, 3, 30, 0, 0),
 datetime.datetime(2024, 3, 29, 0, 0),
 datetime.datetime(2024, 3, 28, 0, 0),
 datetime.datetime(2024, 3, 28, 0, 0),
 datetime.datetime(2024, 3, 28, 0, 0),
 datetime.datetime(2024, 3, 28, 0, 0),
 datetime.datetime(2024, 3, 28, 0, 0),
 datetime.datetime(2024, 3, 27, 0, 0),
 datetime.datetime(2024, 3, 27, 0, 0),
 datetime.datetime(2024, 3, 27, 0, 0),
 datetime.datetime(2024, 3, 27, 0, 0),
 datetime.datetime(2024, 3, 27, 0, 0),
 datetime.datetime(2024, 3, 27, 0, 0),
 datetime.datetime(2024, 3, 26, 0, 0),
 datetime.datetime(2024, 3, 26, 0, 0),
 datetime.datetime(2024, 3, 26, 0, 0),
 datetime.datetime(2024, 3, 26, 0, 0),
 datetime.datetime(2024, 3, 25, 0, 0),
 datetime.datetime(2024, 3, 25, 0, 0),
 datetime.datetime(2024, 3, 21, 0, 0),
 datetime.datetime(2024, 3, 20, 0, 0),
 datetime.datetime(2024, 3, 20, 0, 0),
 datetime.datetime(2024, 3, 20, 0, 0),
 datetime.datetime(2024, 3, 20, 0, 0),
 datetime.datetime(2024, 3, 20, 0, 0),
 datetime.datetime(2024, 3, 19, 0, 0),
 datetime.datetime(2024, 3, 19, 0, 0),
 datetime.datetime(2024, 3, 19, 0, 0),
 datetime.datetime(2024, 3, 19, 0, 0),
 datetime.datetime(2024, 3, 18, 0, 0),
 datetime.datetime(2024, 3, 18, 0, 0),
 datetime.datetime(2024, 3, 18, 0, 0),
 datetime.datetime(2024, 3, 18, 0, 0),
 datetime.datetime(2024, 3, 16, 0, 0),
 datetime.datetime(2024, 3, 15, 0, 0),
 datetime.datetime(2024, 3, 15, 0, 0),
 datetime.datetime(2024, 3, 14, 0, 0),
 datetime.datetime(2024, 3, 14, 0, 0),
 datetime.datetime(2024, 3, 13, 0, 0),
 datetime.datetime(2024, 3, 13, 0, 0),
 datetime.datetime(2024, 3, 13, 0, 0),
 datetime.datetime(2024, 3, 13, 0, 0),
 datetime.datetime(2024, 3, 12, 0, 0),
 datetime.datetime(2024, 3, 11, 0, 0),
 datetime.datetime(2024, 3, 11, 0, 0),
 datetime.datetime(2024, 3, 11, 0, 0),
 datetime.datetime(2024, 3, 7, 0, 0),
 datetime.datetime(2024, 3, 7, 0, 0),
 datetime.datetime(2024, 3, 7, 0, 0),
 datetime.datetime(2024, 3, 6, 0, 0),
 datetime.datetime(2024, 3, 6, 0, 0),
 datetime.datetime(2024, 3, 6, 0, 0),
 datetime.datetime(2024, 3, 5, 0, 0),
 datetime.datetime(2024, 3, 5, 0, 0),
 datetime.datetime(2024, 3, 4, 0, 0),
 datetime.datetime(2024, 3, 4, 0, 0),
 datetime.datetime(2024, 3, 3, 0, 0),
 datetime.datetime(2024, 3, 2, 0, 0),
 datetime.datetime(2024, 3, 2, 0, 0),
 datetime.datetime(2024, 3, 2, 0, 0),
 datetime.datetime(2024, 3, 1, 0, 0),
 datetime.datetime(2024, 3, 1, 0, 0),
 datetime.datetime(2024, 3, 1, 0, 0),
 datetime.datetime(2024, 3, 1, 0, 0),
 datetime.datetime(2024, 2, 29, 0, 0),
 datetime.datetime(2024, 2, 28, 0, 0),
 datetime.datetime(2024, 2, 28, 0, 0),
 datetime.datetime(2024, 2, 27, 0, 0),
 datetime.datetime(2024, 2, 26, 0, 0),
 datetime.datetime(2024, 2, 26, 0, 0),
 datetime.datetime(2024, 2, 26, 0, 0),
 datetime.datetime(2024, 2, 24, 0, 0),
 datetime.datetime(2024, 2, 23, 0, 0),
 datetime.datetime(2024, 2, 23, 0, 0),
 datetime.datetime(2024, 2, 23, 0, 0),
 datetime.datetime(2024, 2, 23, 0, 0),
 datetime.datetime(2024, 2, 23, 0, 0),
 datetime.datetime(2024, 2, 23, 0, 0),
 datetime.datetime(2024, 2, 22, 0, 0),
 datetime.datetime(2024, 2, 22, 0, 0),
 datetime.datetime(2024, 2, 21, 0, 0),
 datetime.datetime(2024, 2, 21, 0, 0),
 datetime.datetime(2024, 2, 21, 0, 0),
 datetime.datetime(2024, 2, 21, 0, 0),
 datetime.datetime(2024, 2, 21, 0, 0),
 datetime.datetime(2024, 2, 20, 0, 0),
 datetime.datetime(2024, 2, 20, 0, 0),
 datetime.datetime(2024, 2, 20, 0, 0),
 datetime.datetime(2024, 2, 20, 0, 0),
 datetime.datetime(2024, 2, 20, 0, 0),
 datetime.datetime(2024, 2, 20, 0, 0),
 datetime.datetime(2024, 2, 20, 0, 0),
 datetime.datetime(2024, 2, 19, 0, 0),
 datetime.datetime(2024, 2, 19, 0, 0),
 datetime.datetime(2024, 2, 18, 0, 0),
 datetime.datetime(2024, 2, 17, 0, 0),
 datetime.datetime(2024, 2, 17, 0, 0),
 datetime.datetime(2024, 2, 16, 0, 0),
 datetime.datetime(2024, 2, 15, 0, 0),
 datetime.datetime(2024, 2, 15, 0, 0),

In [98]:
date2 = data_frame_data.copy()

In [99]:
date2.date = date_nueva

In [100]:
date2

,date,title,real_news,ma,axp,cof
0,2026-02-08,Visa and Mastercard Execs Recently Dismissed S...,Visa and Mastercard executives have dismissed ...,negative,None,None
1,2026-02-04,Behavioral Biometrics Market to Reach US$ 18.3...,The global behavioral biometrics market is pro...,positive,None,None
2,2026-02-03,Here's Why Mastercard Stock Is Still a Buy Des...,Despite regulatory headwinds from a proposed 1...,positive,negative,negative
3,2026-02-02,Why a 2.1% Portfolio Shift Targets a New ETF W...,Capital Planning LLC initiated a new position ...,positive,None,None
4,2026-02-01,Affiance Financial Bets $43 Million on Chuck A...,Affiance Financial initiated a new $43 million...,positive,None,None
...,...,...,...,...,...,...
936,2023-07-13,FIS or MA: Which Is the Better Value Stock Rig...,FIS vs. MA: Which Stock Is the Better Value Op...,None,None,None
937,2023-07-13,Netflix To Rally More Than 11%? Here Are 10 Ot...,Mizuho boosted the price target for Gulfport ...,None,None,None
938,2023-07-13,1 Spectacular Warren Buffett Dividend Stock Th...,Warren Buffett is not against investing in div...,None,None,None
939,2023-07-11,MasterCard (MA) Outpaces Stock Market Gains: W...,"In the latest trading session, MasterCard (MA)...",None,None,None
940,2023-07-11,Mastercard (MA) & JazzCash to Speed Up Digitiz...,Mastercard (MA) partners with JazzCash to driv...,None,None,None

In [101]:
date2.to_csv("./csv/datos_2023-07-10_a_2026-02-04_con_noticias.csv")