In [13]:
import pandas as pd

In [36]:
import os as os

In [41]:
import requests

In [14]:
missing_dates = pd.read_csv("./data/fechas_faltantes.csv")

In [15]:
missing_dates

     Unnamed: 0                    0
0             0  2023-07-12 00:00:00
1             1  2023-07-29 00:00:00
2             2  2023-07-30 00:00:00
3             3  2023-08-01 00:00:00
4             4  2023-08-06 00:00:00
..          ...                  ...
472         472  2026-01-22 00:00:00
473         473  2026-01-24 00:00:00
474         474  2026-01-25 00:00:00
475         475  2026-01-26 00:00:00
476         476  2026-01-31 00:00:00

[477 rows x 2 columns]

In [16]:
missing_dates.drop(columns="Unnamed: 0", inplace= True)

In [ ]:
missing_dates.rename(columns={"0":"dates"}, inplace= True)

In [30]:
missing_dates

                   dates
0    2023-07-12 00:00:00
1    2023-07-29 00:00:00
2    2023-07-30 00:00:00
3    2023-08-01 00:00:00
4    2023-08-06 00:00:00
..                   ...
472  2026-01-22 00:00:00
473  2026-01-24 00:00:00
474  2026-01-25 00:00:00
475  2026-01-26 00:00:00
476  2026-01-31 00:00:00

[477 rows x 1 columns]

In [34]:
prepared_dates = list(map(lambda date: str(date)[:10],list(missing_dates.dates)))

In [35]:
prepared_dates

['2023-07-12',
 '2023-07-29',
 '2023-07-30',
 '2023-08-01',
 '2023-08-06',
 '2023-08-13',
 '2023-08-20',
 '2023-08-24',
 '2023-08-26',
 '2023-08-29',
 '2023-08-30',
 '2023-09-05',
 '2023-09-06',
 '2023-09-08',
 '2023-09-11',
 '2023-09-17',
 '2023-09-24',
 '2023-10-07',
 '2023-10-08',
 '2023-10-10',
 '2023-10-11',
 '2023-10-21',
 '2023-11-02',
 '2023-11-06',
 '2023-11-19',
 '2023-11-20',
 '2023-11-25',
 '2023-11-26',
 '2023-12-03',
 '2023-12-08',
 '2023-12-23',
 '2023-12-24',
 '2023-12-26',
 '2023-12-30',
 '2024-01-04',
 '2024-01-06',
 '2024-01-07',
 '2024-01-17',
 '2024-01-19',
 '2024-01-21',
 '2024-02-08',
 '2024-02-09',
 '2024-02-10',
 '2024-02-12',
 '2024-02-14',
 '2024-02-25',
 '2024-03-08',
 '2024-03-09',
 '2024-03-10',
 '2024-03-17',
 '2024-03-22',
 '2024-03-23',
 '2024-03-24',
 '2024-04-08',
 '2024-04-13',
 '2024-04-14',
 '2024-04-20',
 '2024-04-21',
 '2024-04-23',
 '2024-05-05',
 '2024-05-11',
 '2024-05-14',
 '2024-05-18',
 '2024-05-19',
 '2024-05-25',
 '2024-05-26',
 '2024-06-01',
 '2024-06-08',
 '2024-06-09',
 '2024-06-11',
 '2024-06-13',
 '2024-06-15',
 '2024-06-16',
 '2024-06-17',
 '2024-06-21',
 '2024-06-23',
 '2024-06-30',
 '2024-07-02',
 '2024-07-06',
 '2024-07-07',
 '2024-07-11',
 '2024-07-13',
 '2024-07-14',
 '2024-07-17',
 '2024-07-18',
 '2024-07-19',
 '2024-07-20',
 '2024-07-21',
 '2024-07-23',
 '2024-07-25',
 '2024-07-26',
 '2024-07-27',
 '2024-07-30',
 '2024-08-04',
 '2024-08-05',
 '2024-08-06',
 '2024-08-08',
 '2024-08-10',
 '2024-08-11',
 '2024-08-13',
 '2024-08-14',
 '2024-08-18',
 '2024-08-19',
 '2024-08-20',
 '2024-08-21',
 '2024-08-22',
 '2024-08-23',
 '2024-08-24',
 '2024-08-25',
 '2024-08-27',
 '2024-08-28',
 '2024-08-29',
 '2024-08-30',
 '2024-09-01',
 '2024-09-02',
 '2024-09-04',
 '2024-09-06',
 '2024-09-08',
 '2024-09-10',
 '2024-09-14',
 '2024-09-15',
 '2024-09-16',
 '2024-09-17',
 '2024-09-19',
 '2024-09-20',
 '2024-09-21',
 '2024-09-22',
 '2024-09-23',
 '2024-09-24',
 '2024-09-25',
 '2024-09-28',
 '2024-09-29',
 '2024-09-30',
 '2024-10-01',
 '2024-10-02',
 '2024-10-03',
 '2024-10-04',
 '2024-10-05',
 '2024-10-06',
 '2024-10-10',
 '2024-10-12',
 '2024-10-14',
 '2024-10-15',
 '2024-10-17',
 '2024-10-18',
 '2024-10-19',
 '2024-10-20',
 '2024-10-21',
 '2024-10-22',
 '2024-10-23',
 '2024-10-24',
 '2024-10-25',
 '2024-10-26',
 '2024-10-27',
 '2024-10-28',
 '2024-10-30',
 '2024-10-31',
 '2024-11-01',
 '2024-11-02',
 '2024-11-03',
 '2024-11-05',
 '2024-11-06',
 '2024-11-07',
 '2024-11-08',
 '2024-11-09',
 '2024-11-10',
 '2024-11-11',
 '2024-11-13',
 '2024-11-15',
 '2024-11-20',
 '2024-11-21',
 '2024-11-22',
 '2024-11-23',
 '2024-11-24',
 '2024-11-25',
 '2024-11-27',
 '2024-11-28',
 '2024-12-01',
 '2024-12-02',
 '2024-12-03',
 '2024-12-04',
 '2024-12-05',
 '2024-12-06',
 '2024-12-07',
 '2024-12-08',
 '2024-12-09',
 '2024-12-10',
 '2024-12-13',
 '2024-12-14',
 '2024-12-15',
 '2024-12-16',
 '2024-12-17',
 '2024-12-18',
 '2024-12-19',
 '2024-12-21',
 '2024-12-23',
 '2024-12-26',
 '2024-12-27',
 '2024-12-28',
 '2024-12-29',
 '2024-12-30',
 '2024-12-31',
 '2025-01-01',
 '2025-01-02',
 '2025-01-03',
 '2025-01-04',
 '2025-01-05',
 '2025-01-06',
 '2025-01-07',
 '2025-01-08',
 '2025-01-09',
 '2025-01-10',
 '2025-01-11',
 '2025-01-12',
 '2025-01-13',
 '2025-01-15',
 '2025-01-18',
 '2025-01-19',
 '2025-01-20',
 '2025-01-21',
 '2025-01-23',
 '2025-01-26',
 '2025-01-29',
 '2025-02-01',
 '2025-02-02',
 '2025-02-07',
 '2025-02-08',
 '2025-02-09',
 '2025-02-10',
 '2025-02-12',
 '2025-02-14',
 '2025-02-15',
 '2025-02-16',
 '2025-02-18',
 '2025-02-20',
 '2025-02-21',
 '2025-02-22',
 '2025-02-23',
 '2025-02-24',
 '2025-02-25',
 '2025-02-27',
 '2025-02-28',
 '2025-03-01',
 '2025-03-02',
 '2025-03-03',
 '2025-03-04',
 '2025-03-05',
 '2025-03-06',
 '2025-03-07',
 '2025-03-08',
 '2025-03-09',
 '2025-03-10',
 '2025-03-11',
 '2025-03-12',
 '2025-03-13',
 '2025-03-14',
 '2025-03-15',
 '2025-03-16',
 '2025-03-17',
 '2025-03-19',
 '2025-03-20',
 '2025-03-21',
 '2025-03-22',
 '2025-03-23',
 '2025-03-24',
 '2025-03-25',
 '2025-03-26',
 '2025-03-27',
 '2025-03-28',
 '2025-03-29',
 '2025-03-31',
 '2025-04-01',
 '2025-04-02',
 '2025-04-03',
 '2025-04-04',
 '2025-04-08',
 '2025-04-09',
 '2025-04-10',
 '2025-04-11',
 '2025-04-12',
 '2025-04-14',
 '2025-04-15',
 '2025-04-18',
 '2025-04-19',
 '2025-04-20',
 '2025-04-22',
 '2025-04-25',
 '2025-04-26',
 '2025-04-27',
 '2025-04-30',
 '2025-05-02',
 '2025-05-03',
 '2025-05-04',
 '2025-05-05',
 '2025-05-06',
 '2025-05-07',
 '2025-05-08',
 '2025-05-09',
 '2025-05-10',
 '2025-05-11',
 '2025-05-12',
 '2025-05-14',
 '2025-05-15',
 '2025-05-16',
 '2025-05-17',
 '2025-05-18',
 '2025-05-19',
 '2025-05-20',
 '2025-05-21',
 '2025-05-22',
 '2025-05-24',
 '2025-05-25',
 '2025-05-26',
 '2025-05-27',
 '2025-05-28',
 '2025-05-29',
 '2025-05-30',
 '2025-05-31',
 '2025-06-01',
 '2025-06-02',
 '2025-06-03',
 '2025-06-04',
 '2025-06-05',
 '2025-06-06',
 '2025-06-07',
 '2025-06-08',
 '2025-06-09',
 '2025-06-10',
 '2025-06-14',
 '2025-06-15',
 '2025-06-16',
 '2025-06-17',
 '2025-06-18',
 '2025-06-19',
 '2025-06-20',
 '2025-06-21',
 '2025-06-22',
 '2025-06-23',
 '2025-06-24',
 '2025-06-25',
 '2025-06-26',
 '2025-06-29',
 '2025-06-30',
 '2025-07-01',
 '2025-07-02',
 '2025-07-03',
 '2025-07-05',
 '2025-07-06',
 '2025-07-07',
 '2025-07-08',
 '2025-07-09',
 '2025-07-10',
 '2025-07-13',
 '2025-07-17',
 '2025-07-19',
 '2025-07-20',
 '2025-07-22',
 '2025-07-24',
 '2025-07-25',
 '2025-07-26',
 '2025-07-27',
 '2025-07-30',
 '2025-08-01',
 '2025-08-02',
 '2025-08-03',
 '2025-08-04',
 '2025-08-05',
 '2025-08-06',
 '2025-08-07',
 '2025-08-08',
 '2025-08-09',
 '2025-08-10',
 '2025-08-11',
 '2025-08-13',
 '2025-08-14',
 '2025-08-16',
 '2025-08-17',
 '2025-08-19',
 '2025-08-23',
 '2025-08-24',
 '2025-08-25',
 '2025-08-26',
 '2025-08-29',
 '2025-08-30',
 '2025-08-31',
 '2025-09-03',
 '2025-09-04',
 '2025-09-05',
 '2025-09-06',
 '2025-09-07',
 '2025-09-08',
 '2025-09-09',
 '2025-09-10',
 '2025-09-11',
 '2025-09-12',
 '2025-09-14',
 '2025-09-16',
 '2025-09-18',
 '2025-09-19',
 '2025-09-21',
 '2025-09-22',
 '2025-09-23',
 '2025-09-24',
 '2025-09-25',
 '2025-09-26',
 '2025-09-27',
 '2025-09-28',
 '2025-10-01',
 '2025-10-02',
 '2025-10-04',
 '2025-10-05',
 '2025-10-06',
 '2025-10-09',
 '2025-10-12',
 '2025-10-15',
 '2025-10-16',
 '2025-10-18',
 '2025-10-19',
 '2025-10-20',
 '2025-10-22',
 '2025-10-23',
 '2025-10-24',
 '2025-10-25',
 '2025-10-26',
 '2025-10-29',
 '2025-11-05',
 '2025-11-07',
 '2025-11-08',
 '2025-11-09',
 '2025-11-10',
 '2025-11-11',
 '2025-11-12',
 '2025-11-14',
 '2025-11-15',
 '2025-11-16',
 '2025-11-17',
 '2025-11-18',
 '2025-11-20',
 '2025-11-21',
 '2025-11-23',
 '2025-11-29',
 '2025-11-30',
 '2025-12-02',
 '2025-12-04',
 '2025-12-05',
 '2025-12-06',
 '2025-12-07',
 '2025-12-08',
 '2025-12-09',
 '2025-12-10',
 '2025-12-11',
 '2025-12-12',
 '2025-12-14',
 '2025-12-15',
 '2025-12-16',
 '2025-12-17',
 '2025-12-20',
 '2025-12-21',
 '2025-12-23',
 '2025-12-24',
 '2025-12-25',
 '2025-12-26',
 '2025-12-27',
 '2025-12-28',
 '2025-12-29',
 '2025-12-31',
 '2026-01-03',
 '2026-01-05',
 '2026-01-07',
 '2026-01-09',
 '2026-01-14',
 '2026-01-17',
 '2026-01-22',
 '2026-01-24',
 '2026-01-25',
 '2026-01-26',
 '2026-01-31']

In [43]:
api_key = os.getenv("API_KEY")

In [46]:
def get_config(date):
    return{
        "ticker": "MA",
        "published_utc": date,
        "limit":"5",
        "apiKey":api_key
    }

In [58]:
getted_news = []

In [59]:
import time

In [60]:
for date in prepared_dates:
    try: 
        getted_news.append(requests.get("https://api.massive.com/v2/reference/news", params= get_config(date)))
        time.sleep(2)
    except Exception as e:
        print(f"no se pudo hacer esto, ya que: {e}")

In [92]:
print([new.json() for new in getted_news])

[{'results': [], 'status': 'OK', 'request_id': '857d2bab57979b869429f0d70d793873'}, {'results': [], 'status': 'OK', 'request_id': '5e15b13ecbd6fecfa8243f56bee809ad'}, {'results': [], 'status': 'OK', 'request_id': '260ec5eb4220afe9839389ac8f779e3c'}, {'results': [], 'status': 'OK', 'request_id': '2ea4298e2bf0354f1286bfd6ecbdc972'}, {'results': [], 'status': 'OK', 'request_id': '4125d73499caf0128ab75c860f4beee4'}, {'status': 'ERROR', 'request_id': 'd7e6be4b7a55436fb7e63301184540f9', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': 'd13002b3b2df315c8dcc5722aa3bd1f4', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': '48c15587751f25574518880b10ebbd45', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': '7081d1dca352eb5a334e0179615cd000', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': '4d3dd8ea1d4c27a12b3174f9238cc11e', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': '7035d16e789ceadc9cc9493f2ee8d4e5', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': '0406f20217e89c2377390856bdcadc4a', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': '9ae4e36a001433719a24f508b0acc134', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': '0c2f338975a5116e4846cac513d2e196', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': '51724b3c2ef349bf33960491d6123166', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'results': [], 'status': 'OK', 'request_id': '1799f924e789e0246071fc9d4fb53244'}, {'results': [], 'status': 'OK', 'request_id': 'cfa72d1a64ccb725c628b0123b62813e'}, {'results': [], 'status': 'OK', 'request_id': '433c7b673329a2e19c59ddffcff3e55a'}, {'results': [], 'status': 'OK', 'request_id': '2fe6e808036b17414f8369efd245c6c3'}, {'results': [], 'status': 'OK', 'request_id': '0490cb5015a3324a32e49baf87a4591d'}, {'status': 'ERROR', 'request_id': '59a314b60f2d22e073db7303fd4a0ec1', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': 'b92e5dd22e014ad1d8127cc0774e9319', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': 'dd9376a36c49e3a5b9ebd5a2214ce8b0', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': '82028338a16c9a1c9f748c51be8c7c02', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': 'bf6cfdfa92f5ecdbb111902a7fb678d9', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': '1e16f16416c4f932a049f1be8b1ba91c', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': '5206a988da73209c5a373bb71b49cc16', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': '652c7f3a1788fbfef0f118e52c12b9f4', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': 'f162795636aa9ce3dbdd8e957d8e5295', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': '0b4df66b32b547e27c9f60d110da34d1', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': 'f03aed92fbf1e6672f18b8a2fb54f4a3', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': '8ffee257c6931ca894db23798304504a', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': 'fbf3adafeedad2b3cd713c792ed3c8fb', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': '3d3d6d0b9b748a4420910ce64b6bb20c', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': 'c94d38a8995c85ecbf09d0fdf9deb485', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': '802c88d52867ee5182d76df754d1aeaf', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': '545d5e8fb9d6dc4f64b7465047cb05f0', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': 'c633d91e968aa4073d2597ac8db33747', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': 'ab2307e44b37d90c1468734c9545eb99', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'results': [], 'status': 'OK', 'request_id': '08fb8a6fe5f735b81b915e10a4e8bb7a'}, {'results': [], 'status': 'OK', 'request_id': 'f50d6f9dfd9e6b9ad1630464cf702a2d'}, {'results': [], 'status': 'OK', 'request_id': '0598cf9cb783263004fccd96c371885b'}, {'results': [], 'status': 'OK', 'request_id': 'cbc405795a535396e56e4bcf0d43a671'}, {'results': [], 'status': 'OK', 'request_id': 'e0366923375798245e60eec05dd30219'}, {'status': 'ERROR', 'request_id': 'db5553a29b33325bb6d76af6dbbc5ba4', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': '50d36f78527d99f1760e8b17c5cb0405', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': '3333bfe270a2c828c69dd58d9f99fe90', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': '487beacb5a61ad40f039675835e2919d', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': '95a22b859556cc8d9ba0981172121b6a', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': '02dfc2cab5d986def8c89986e793025c', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': 'c7432a460a967dac0a2d56077eff3cd5', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': 'dfd37e5cf8d9f4dc4bc6db25fc430bb4', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': 'f2e02c6f74daad9196af05b860657550', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': '37b744cfe3de4bb67dccf46a103f04d4', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': '151ffd16910fd54c8bfb6168644d6389', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': '7bc7323db12c8d05b995aa11eb8fca53', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': 'becbca8f34baa0c80b7c51dc30b615b7', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': '0333a60fe3b439e71cf4d829c337db5e', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': '798516cda165dce4816bd9ccc547af7e', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': 'c7bb90a92f1ac7b963ed653ff24b2a13', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': '274430abddcf3bad10662182a28ee82f', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': '9fe5a30d6cc1cc94b93e03e2e3f6af43', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': '4d470f87870ad0edba812da98960f669', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'results': [], 'status': 'OK', 'request_id': '18181447333a410808bdc7f3fbc0b339'}, {'results': [], 'status': 'OK', 'request_id': 'd2227e8b33d1a1be6eb9ce3d22d54d4d'}, {'results': [], 'status': 'OK', 'request_id': '9f03ec5e8993af4c4c75237e6d54832c'}, {'results': [], 'status': 'OK', 'request_id': '1308139246aeca23fbd2f597dcff0438'}, {'results': [], 'status': 'OK', 'request_id': '5d6f82f04f7e2de0056fe68a9d16f880'}, {'status': 'ERROR', 'request_id': '4bfa74254c77aa5854d79789bf0dcb4e', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': '2956e3ce224ddd95a876a13314879fba', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': 'eb53b2c1822002cd957fd76cd21050fa', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': '8c31e2c3a22ba5905cfb5c3c809696b4', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': '0570dbed64470d9f81329410f3a56d8d', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': '51e60d6cd77d5a4b22e15dcf14690478', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': '30216382d9492cc9c24aa0deaf21aeac', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': '21659cd12c8c1c6275cbe5564a3c1136', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': '5b7a2f356a1a845fdbb676f691c59d12', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': 'cca77cc6b8d9f2794812864a60e64cbd', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': '824cd336203de0a2479dbccc36641cd8', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': 'c0801d0a011d2c21f21dbd8c376e703e', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': '741040d440bc005d6fa31ca45d90acf1', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': '326410e1bc0d35a0606dc7dfcafdfc2d', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': 'b7661678f205d2b73bd8c37678651456', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': 'bac138399bc2d156c4e01c90db49f9f9', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': '42200c0577811eecdb95a9c9c0b8dc85', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': 'dd79dabe068ea0843fded74da8ed5cba', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': 'a6e69b9a0e71e7a20f1ef4077854c35f', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': '71758e3ae7cc394aefb86666736db60f', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'results': [], 'status': 'OK', 'request_id': '2a79682b429ac5001bb6d0145196fc2d'}, {'results': [], 'status': 'OK', 'request_id': 'c998db41ad90d572c639db611aa049b3'}, {'results': [], 'status': 'OK', 'request_id': '9ce3b290ddab798fffede78191233f17'}, {'results': [], 'status': 'OK', 'request_id': '64722a9a5a06b169b8fbd29bced1a7d3'}, {'results': [], 'status': 'OK', 'request_id': '0178dd139e59ab4ec98e3ea328281751'}, {'status': 'ERROR', 'request_id': '9fa6ec5963440f0f208031693b8b6cee', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': 'ce8ee45ac33b400036c9fc1477c753ac', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': '0552a7cfdc527ca274ab1a4c92796d10', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': '340b65c9e18cd6f09960db08a9d29cec', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': '40138ada94ae519eff8d14aa74d70b9a', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': '1dc09bf32e687d68744bf2dc5b7e958d', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': 'cecd1c3ae05fcddf1512e45f83203e43', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': 'f3aeaf43af6de3d6ed984efd590bf970', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': '2dd1170f3c26d797e3a10337a7e32c15', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': '83acc7b1b2996d3d74d193ddca3a7726', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': '91370d36ff4ad2966150bbb2b69d8353', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': '08a198e329e0b610ca593c5faed90185', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': '1f9df4881a6b6d9d28b9363d928da93c', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': '6c7d1cb7a7a846977681cfed770172d9', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': 'ecfc787800caf9cd05f78bfce61b7262', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id': '231396872e4bea3b535c741b649a8b32', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}, {'status': 'ERROR', 'request_id'

In [88]:
success = []

In [89]:
getted_news[0].json()

{'results': [],
 'status': 'OK',
 'request_id': '857d2bab57979b869429f0d70d793873'}

In [90]:
for notice in getted_news:
    if notice.status_code == 200:
        data = notice.json()
        if data.get('results'): 
            success.append(notice)

In [94]:
success[0].json()

{'results': [{'id': '83cf874b957dcffc25707d9f5e6b8f1c471dcddadb530bb2556197aa5a3f6fb3',
   'publisher': {'name': 'The Motley Fool',
    'homepage_url': 'https://www.fool.com/',
    'logo_url': 'https://s3.massive.com/public/assets/news/logos/themotleyfool.svg',
    'favicon_url': 'https://s3.massive.com/public/assets/news/favicons/themotleyfool.ico'},
   'title': 'Best Stocks to Buy Before 2025: Visa Stock vs. Mastercard Stock',
   'author': 'N/A',
   'published_utc': '2024-12-09T15:25:42Z',
   'article_url': 'https://www.fool.com/investing/2024/12/09/best-stocks-to-buy-before-2025-visa-stock-vs-maste/?source=iedfolrf0000001',
   'tickers': ['MA', 'V'],
   'image_url': 'https://g.foolcdn.com/editorial/images/800326/stock-market-data-with-uptrend-vector.jpg',
   'description': 'The Motley Fool is a financial services company founded in 1993, dedicated to providing investing solutions, personal finance education, and market analysis to millions of people through its various platforms.',
   'keywords': ['financial services',
    'investing',
    'personal finance',
    'market analysis'],
   'insights': [{'ticker': 'MA',
     'sentiment': 'positive',
     'sentiment_reasoning': 'The Motley Fool has positions in and recommends Mastercard, indicating a positive sentiment towards the company.'},
    {'ticker': 'V',
     'sentiment': 'positive',
     'sentiment_reasoning': 'The Motley Fool has positions in and recommends Visa, indicating a positive sentiment towards the company.'}]}],
 'status': 'OK',
 'request_id': 'f872344bbb4e7a91f94dabb4906fbd22',
 'count': 1}